import { IntlMessageFormat } from 'intl-messageformat';

type MessageFormatElement = ConstructorParameters<typeof IntlMessageFormat>[0] extends
  | string
  | (infer U)[]
  ? U
  : never;

const RESERVED = new Set([
  // Javascript
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'implements',
  'interface',
  'let',
  'package',
  'private',
  'protected',
  'public',
  'static',
  'yield',
  'enum',
  'await',
  // Types
  'number',
  // Utility
  'key',
  'type',
]);

export type TypeMap = Map<string, Node>;

export type Node = {
  key?: string;
  type?: string;
  children: TypeMap;
};

const typeMap: TypeMap = new Map();

export function generateTypes(localization: Map<string, MessageFormatElement[]>) {
  for (const [id, ast] of localization) {
    const path = id.split('.');
    const last = path[path.length - 1];
    try {
      let current = typeMap;
      for (const step of path.slice(0, -1)) {
        current = ensureNode(current, step).children;
      }
      const node = ensureNode(current, last);
      node.key = id;
      node.type = generateType(extractParams(ast));
    } catch (e) {
      console.error(`Failed to generate type for ${id}:`, ast, e);
    }
  }
  let out = '/* eslint-disable @typescript-eslint/no-namespace */\n';
  out +=
    '// This file is automatically generated by @src/infrastructure/shell/generate-localization-types\n';
  out += '// Generated on ' + new Date().toISOString() + '\n';
  return (out += emitTypes(typeMap));
}

function emitTypes(map: TypeMap): string {
  let out = '';
  for (const [key, node] of map) {
    const sanitizedKey = sanitizeIdent(key);
    out += `export namespace ${sanitizedKey} {\n`;
    if (node.key) {
      out += `export const key = '${node.key}';\n`;
    }
    if (node.type) {
      out += `export type parameter = ${node.type};\n`;
    }
    if (node.children.size > 0) {
      out += indent(emitTypes(node.children));
    }
    out += `}\n`;
  }

  return out;
}

export function sanitizeIdent(s: string): string {
  // Replace invalid chars with _
  s = s.replace(/[^a-zA-Z0-9_$]/g, '_');
  // Cannot start with number
  if (/^[0-9]/.test(s)) {
    s = '_' + s;
  }
  // Empty fallback
  if (!s) {
    s = '_';
  }
  // Avoid reserved words
  if (RESERVED.has(s)) {
    s = `_${s}`;
  }
  return s;
}

function ensureNode(map: TypeMap, key: string): Node {
  let node = map.get(key);
  if (!node) {
    node = { children: new Map() };
    map.set(key, node);
  }
  return node;
}

function indent(str: string): string {
  return str
    .split('\n')
    .map(l => (l ? '  ' + l : l))
    .join('\n');
}

function extractParams(ast: MessageFormatElement[]): Set<string> {
  const params = new Set<string>();

  function visit(nodes: MessageFormatElement[]) {
    for (const n of nodes) {
      // Argument
      if (n.type === 1) {
        params.add(n.value);
        continue;
      }
      // ICU select/plural (only when options exist)
      if (n.type === 6 || n.type === 7 || (n.type === 8 && 'options' in n && n.options)) {
        params.add(n['value']);
        for (const key in n['options']) {
          visit(n['options'][key].value);
        }
        continue;
      }
      // Custom tag-like node
      if ('children' in n && Array.isArray(n.children)) {
        visit(n.children);
      }
    }
  }
  visit(ast);
  return params;
}

function generateType(params: Set<string>): string {
  const fields = [...params].map(p => `  ${p}: string;`).join('\n');
  if (!fields) {
    return 'object';
  }

  return `{\n${fields}\n}`;
}
